//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Service.DTOs
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomDTO", Namespace="http://schemas.datacontract.org/2004/07/Hotel.Service.DTOs")]
    public partial class RoomDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int NumberField;
        
        private int QuantityField;
        
        private bool ReservedField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Reserved
        {
            get
            {
                return this.ReservedField;
            }
            set
            {
                this.ReservedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuestDTO", Namespace="http://schemas.datacontract.org/2004/07/Hotel.Service.DTOs")]
    public partial class GuestDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EmailField;
        
        private int IdField;
        
        private string NameField;
        
        private string PhoneField;
        
        private string SurnameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname
        {
            get
            {
                return this.SurnameField;
            }
            set
            {
                this.SurnameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IHotelService")]
public interface IHotelService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/Registered", ReplyAction="http://tempuri.org/IHotelService/RegisteredResponse")]
    string Registered();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/Registered", ReplyAction="http://tempuri.org/IHotelService/RegisteredResponse")]
    System.Threading.Tasks.Task<string> RegisteredAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/GetRooms", ReplyAction="http://tempuri.org/IHotelService/GetRoomsResponse")]
    Hotel.Service.DTOs.RoomDTO[] GetRooms();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/GetRooms", ReplyAction="http://tempuri.org/IHotelService/GetRoomsResponse")]
    System.Threading.Tasks.Task<Hotel.Service.DTOs.RoomDTO[]> GetRoomsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/GetAvailableRooms", ReplyAction="http://tempuri.org/IHotelService/GetAvailableRoomsResponse")]
    Hotel.Service.DTOs.RoomDTO[] GetAvailableRooms();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/GetAvailableRooms", ReplyAction="http://tempuri.org/IHotelService/GetAvailableRoomsResponse")]
    System.Threading.Tasks.Task<Hotel.Service.DTOs.RoomDTO[]> GetAvailableRoomsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/GetGuests", ReplyAction="http://tempuri.org/IHotelService/GetGuestsResponse")]
    Hotel.Service.DTOs.GuestDTO[] GetGuests();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/GetGuests", ReplyAction="http://tempuri.org/IHotelService/GetGuestsResponse")]
    System.Threading.Tasks.Task<Hotel.Service.DTOs.GuestDTO[]> GetGuestsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/RoomReservation", ReplyAction="http://tempuri.org/IHotelService/RoomReservationResponse")]
    void RoomReservation(System.DateTime arrival, System.DateTime departure, string guestNameSurname, int roomNumber);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/RoomReservation", ReplyAction="http://tempuri.org/IHotelService/RoomReservationResponse")]
    System.Threading.Tasks.Task RoomReservationAsync(System.DateTime arrival, System.DateTime departure, string guestNameSurname, int roomNumber);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IHotelServiceChannel : IHotelService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HotelServiceClient : System.ServiceModel.ClientBase<IHotelService>, IHotelService
{
    
    public HotelServiceClient()
    {
    }
    
    public HotelServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public HotelServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HotelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HotelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string Registered()
    {
        return base.Channel.Registered();
    }
    
    public System.Threading.Tasks.Task<string> RegisteredAsync()
    {
        return base.Channel.RegisteredAsync();
    }
    
    public Hotel.Service.DTOs.RoomDTO[] GetRooms()
    {
        return base.Channel.GetRooms();
    }
    
    public System.Threading.Tasks.Task<Hotel.Service.DTOs.RoomDTO[]> GetRoomsAsync()
    {
        return base.Channel.GetRoomsAsync();
    }
    
    public Hotel.Service.DTOs.RoomDTO[] GetAvailableRooms()
    {
        return base.Channel.GetAvailableRooms();
    }
    
    public System.Threading.Tasks.Task<Hotel.Service.DTOs.RoomDTO[]> GetAvailableRoomsAsync()
    {
        return base.Channel.GetAvailableRoomsAsync();
    }
    
    public Hotel.Service.DTOs.GuestDTO[] GetGuests()
    {
        return base.Channel.GetGuests();
    }
    
    public System.Threading.Tasks.Task<Hotel.Service.DTOs.GuestDTO[]> GetGuestsAsync()
    {
        return base.Channel.GetGuestsAsync();
    }
    
    public void RoomReservation(System.DateTime arrival, System.DateTime departure, string guestNameSurname, int roomNumber)
    {
        base.Channel.RoomReservation(arrival, departure, guestNameSurname, roomNumber);
    }
    
    public System.Threading.Tasks.Task RoomReservationAsync(System.DateTime arrival, System.DateTime departure, string guestNameSurname, int roomNumber)
    {
        return base.Channel.RoomReservationAsync(arrival, departure, guestNameSurname, roomNumber);
    }
}
