//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Service.DTOs
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomDTO", Namespace="http://schemas.datacontract.org/2004/07/Hotel.Service.DTOs")]
    public partial class RoomDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int NumberField;
        
        private int QuantityField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IHotelService")]
public interface IHotelService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/Registered", ReplyAction="http://tempuri.org/IHotelService/RegisteredResponse")]
    string Registered();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/Registered", ReplyAction="http://tempuri.org/IHotelService/RegisteredResponse")]
    System.Threading.Tasks.Task<string> RegisteredAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/GetRooms", ReplyAction="http://tempuri.org/IHotelService/GetRoomsResponse")]
    Hotel.Service.DTOs.RoomDTO[] GetRooms();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/GetRooms", ReplyAction="http://tempuri.org/IHotelService/GetRoomsResponse")]
    System.Threading.Tasks.Task<Hotel.Service.DTOs.RoomDTO[]> GetRoomsAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IHotelServiceChannel : IHotelService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HotelServiceClient : System.ServiceModel.ClientBase<IHotelService>, IHotelService
{
    
    public HotelServiceClient()
    {
    }
    
    public HotelServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public HotelServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HotelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HotelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string Registered()
    {
        return base.Channel.Registered();
    }
    
    public System.Threading.Tasks.Task<string> RegisteredAsync()
    {
        return base.Channel.RegisteredAsync();
    }
    
    public Hotel.Service.DTOs.RoomDTO[] GetRooms()
    {
        return base.Channel.GetRooms();
    }
    
    public System.Threading.Tasks.Task<Hotel.Service.DTOs.RoomDTO[]> GetRoomsAsync()
    {
        return base.Channel.GetRoomsAsync();
    }
}
